                  
############################################################
# +------------------------------------------------------+ #
# |                      shdwMobs                        | #
# +------------------------------------------------------+ #
############################################################

lightningOnSpawn: true

printConsoleSpawns: true

# shdw mob spawn percentage
Percentage: 5

# shdw mob item drop percentage
DropPercentage: 10

# Halloween Drops
shdwWitherSkeleName: 'spookyWitherSkeleton'
halloEventWeapon: '&6&ldeath&8&lSickle'

# shdwEnderman drops
shdwEndermanName: 'spookyEnderman'
BowName: '&ethunderBow'

# shdwZombie drops
shdwZombieName: 'spookyZombie'
ZombieHelmetName: '&6&lspooky&8&lHelmet'

# shdwSkeleton drops
shdwSkeletonName: 'spookySkeleton'
SkeletonChestplateName: '&6&lspooky&8&lChestplate'

# shdwCreeper drops
shdwCreeperName: 'spookyCreeper'
CreeperLeggingsName: '&6&lspooky&8&lLeggings'

# shdwSpider drops
shdwSpiderName: 'spookySpider'
SpiderBootsName: '&6&lspooky&8&lBoots'

# shdwPiglin drops
shdwPiglinName: 'shdwPiglin'
PiglinHelmetName: '&6Piglin &6Crown'

BonerName: '&8Shawn &8Lee &8Boner'

# DrChicken drop
ChickenName: '&9DrChicken'
ChickenPercentage: 3
